name: Build Worker with Sysdig Secure Inline Scan

on:
  push:
    branches:
      - 'main'
    paths:
      - 'worker/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'worker/**'

jobs:
  call-docker-build:

    name: Worker Call Docker Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: dockersamples/.github/.github/workflows/reusable-docker-build.yaml@main
        with:
          ghcr-enable: true
          image-names: |
            ghcr.io/ccconnected/example-voting-app-worker
          tag-rules: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
          context: worker

      - name: Sysdig Secure Inline Scan
        run: |
          docker pull docker.io/sysdig/secure-inline-scan:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src -e INLINE_SCAN_IMAGE=ghcr.io/ccconnected/example-voting-app-worker docker.io/sysdig/secure-inline-scan:latest

    permissions:
      contents: read
      packages: write
      pull-requests: write
